export const CREATE_SONG_REQUEST = "CREATE_SONG_REQUEST";
export const CREATE_SONG_SUCCESS = "CREATE_SONG_SUCCESS";
export const CREATE_SONG_FAILURE = "CREATE_SONG_FAILURE";

export const LIST_SONGS_REQUEST = "LIST_SONGS_REQUEST";
export const LIST_SONGS_SUCCESS = "LIST_SONGS_SUCCESS";
export const LIST_SONGS_FAILURE = "LIST_SONGS_FAILURE";

export const UPDATE_SONG_REQUEST = "UPDATE_SONG_REQUEST";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS";
export const UPDATE_SONG_FAILURE = "UPDATE_SONG_FAILURE";

export const REMOVE_SONG_REQUEST = "REMOVE_SONG_REQUEST";
export const REMOVE_SONG_SUCCESS = "REMOVE_SONG_SUCCESS";
export const REMOVE_SONG_FAILURE = "REMOVE_SONG_FAILURE";

export const GENERATE_STATISTICS_REQUEST = "GENERATE_STATISTICS_REQUEST";
export const GENERATE_STATISTICS_SUCCESS = "GENERATE_STATISTICS_SUCCESS";
export const GENERATE_STATISTICS_FAILURE = "GENERATE_STATISTICS_FAILURE";
